### ISSUE TITLE
Server Side Rendering support

### ISSUE THREAD

**Issue by Al-Rozhkov** [vuikit/vuikit#73]
@gustojs [mentioned earlier](https://github.com/vuikit/vuikit/issues/68#issuecomment-343060725) in #68 that vuikit not yet support SSR. I tried vuikit with [Nuxt](https://github.com/nuxt/nuxt.js) project and it doesn't work indeed.

@gustojs, please share, if you find solution for that.

Lets track updates here and join forces to make vuikit SSR compatible :)

**Comment by miljan-aleksic** [comment]
@Al-Rozhkov, can you put that Nuxt project on a public repository?

**Comment by Al-Rozhkov** [comment]
Please, check out this example project: https://github.com/Al-Rozhkov/nuxt-vuikit

If you start with `npm run dev`, browse to `http://localhost:3000/` and click on links in navbar, everything works perfectly. Because index page doesn't use vuikit components and you start from index. But if you start from other route (e.g. `http://localhost:3000/button`), you'll get an error.

```
{ \vuikit.nuxt\node_modules\vuikit\card.js:7
import { includes } from 'vuikit/core/util';
^^^^^^

SyntaxError: Unexpected token import
...
```

I belive this is because of SSR incompatibility.

**Comment by miljan-aleksic** [comment]
That's actually ES6 transpiling issue. The example project is [setting up Vuikit plugin](https://github.com/Al-Rozhkov/nuxt-vuikit/blob/master/plugins/vuikit.js) but never actually loading it in the nuxt config. Then in order to use Vuikit it's registering the components locally, which is failing because of ES6 code.

I will check that out, meantime remove the local imports and [register](https://nuxtjs.org/api/configuration-plugins) the Plugin. That should fix it.

**Comment by Al-Rozhkov** [comment]
I tried to register the Plugin. See latest commit. The error still there and vendor bundle grows significantly.

It would be great to use selected vuikit components to keep bundle lean.

**Comment by miljan-aleksic** [comment]
Making few tests it seems SSR it expects the modules to be browser ready, example umd. But the goal is to have lean bundles on the fly, which is possible only with ES6. I am afraid that until browsers don't start to natively support ES6 modules the only viable solution to keep the size small and SSR compatible would be a custom bundle. A simple rollup.js bundling a file similar to:

```
import { Button } from 'vuikit/button'
import { Card, CardTitle } from 'vuikit/card'

const Vuikit = {
  install (Vue) {
    Vue.component('VkButton', Button)
    Vue.component('VkCard', Card)
    Vue.component('VkCardTitle', CardTitle)
  }
}

if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(Vuikit)
}

export default Vuikit
```

If I am missing something, please let me know.

**Comment by Al-Rozhkov** [comment]
Sorry, I'm not familiar with rollup yet. I'll try to solve this with webpack first. I'll keep you informed.

**Comment by miljan-aleksic** [comment]
You could use the Vuikit own build process. Commenting the components you don't need in [this](https://github.com/vuikit/vuikit/blob/next/packages/vuikit/src/components/index.js) file and then running the `build` command.

**Comment by david-cahill** [comment]
You can add to your nuxt.config.js if you want to use this in your nuxt project, but of course this is defeating the purpose of SSR, might be useful to test though.

```
plugins: [
    { src: 'plugins/vue-ui-kit.js', ssr: false }
  ]
```

**Comment by miljan-aleksic** [comment]
A new version with SSR support is on the way :)

**Comment by miljan-aleksic** [comment]
Vuikit 0.8.3 with SSR support has been just released!

**Comment by Almusamim** [comment]
@miljan-aleksic how do i implement it with nuxt?

**Comment by miljan-aleksic** [comment]
@Almusamim, check [this example](https://github.com/nuxt/nuxt.js/tree/dev/examples/with-vuikit)
